### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by 4noxx** [belese/ha_integrations#4]
i copied you files now i

get a error if i try to login

**Comment by 4noxx** [comment]
![Image](https://github.com/user-attachments/assets/491844a1-7c45-47d0-b710-5fdc3b9ec556)

**Comment by 4noxx** [comment]
after changeing in config_flow.py
i see my board....

![Image](https://github.com/user-attachments/assets/55645e03-ffe2-4eb1-ad39-74cbe3e6c436)

submit not possible yet

**Comment by 4noxx** [comment]
Login now possible, but all my entities are empty...

![Image](https://github.com/user-attachments/assets/86c25d7a-2424-44d1-9dbd-3dbd232a1ea7)

![Image](https://github.com/user-attachments/assets/8b43c70a-bcae-49a3-9ca8-862b471fd122)

**Comment by RONMAN87** [comment]
Hi, same issue. I cant log in. Is there a solution?

**Comment by belese** [comment]
Sorry, i didn't check recently, maybe there change in upstream api.
If i remember well, a match has to be started to see data, to not spam the autodarts api

**Comment by RONMAN87** [comment]
Hi Belese, thanks for the feedback. Unfortunately, the login doesn't work during a match. I would be very grateful if you could take a look at it. The integration is exactly what I was looking for. Thank you very much. Greetings from Germany.

<img width="1331" alt="Image" src="https://github.com/user-attachments/assets/0eda04f7-1845-4dd2-a9ac-859552ee6713" />

<img width="534" alt="Image" src="https://github.com/user-attachments/assets/cb31bf12-67b4-41a3-97c5-51a09c3a6473" />

**Comment by misy1337** [comment]
In const.py you need to change:
AUTODART_MATCH_URL = "https://play.autodarts.io/matches"

to:
AUTODART_MATCH_URL =  "https://api.autodarts.io/gs/v0/matches"

In addition to that AUTODART_CLIENT_ID  and AUTODART_CLIENT_SECRET needs to be changed. Unfortunately I don't have any valid credentials. If you use my repo the integration is working (beside that I don't have CLIEND_ID / Secret). The only thing I can't solve is that from time to time the integration disconnects from autodarts and needs to be reloaded in order to work.

**Comment by DuchyWare** [comment]
Is this going to be updated? as I am unsure how to change this my end on my local files?

**Comment by a-jey** [comment]
> Is this going to be updated? as I am unsure how to change this my end on my local files?

just open the const.py file with a texteditor.

**Comment by Snago636** [comment]
That did not work for me. :(

![Image](https://github.com/user-attachments/assets/fc81dbf8-5b4c-4f30-8133-6148d9313248)

![Image](https://github.com/user-attachments/assets/1c2445c3-7732-446b-9256-f3ecd72d5554)

HASS was restarted

**Comment by RONMAN87** [comment]
Hi, it doesn't work for me either. Same Issue.

![Image](https://github.com/user-attachments/assets/1446dd23-a507-4fee-8674-5ac2084ec9b5)

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/fe3e8705-9d16-4965-8424-218b6ef1e046" />

I would be really grateful if the problem could be solved.

**Comment by a-jey** [comment]
Try this:
AUTODART_MATCH_URL = 'https://api.autodarts.io/gs/v0/matches/'

instead of that:
AUTODART_MATCH_URL = "https://api.autodarts.io/gs/v0/matches/"

**Comment by Snago636** [comment]
> Try this: AUTODART_MATCH_URL = 'https://api.autodarts.io/gs/v0/matches/'
> 
> instead of that: AUTODART_MATCH_URL = "https://api.autodarts.io/gs/v0/matches/"

Hi, unfortunately it doesn't work. Same error again

**Comment by Snago636** [comment]
`2025-02-27 08:07:43.599 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.0.101
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/autodarts/session.py", line 64, in refresh_token
    self._token = await asyncio.to_thread(self.keycloak_openid.token,self.email, self.password)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/keycloak/keycloak_openid.py", line 375, in token
    return raise_error_from_response(data_raw, KeycloakPostError)
  File "/usr/local/lib/python3.13/site-packages/keycloak/exceptions.py", line 195, in raise_error_from_response
    raise error(
    ...<3 lines>...
    )
keycloak.exceptions.KeycloakAuthenticationError: 401: b'{"error":"invalid_client","error_description":"Invalid client or Invalid client credentials"}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 121, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 340, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 387, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 490, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/autodarts/config_flow.py", line 67, in async_step_user
    self.session = await async_validate_input(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        user_input["email"], user_input["password"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/autodarts/config_flow.py", line 46, in async_validate_input
    if not await session.is_authenticated():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/autodarts/session.py", line 92, in is_authenticated
    token: dict = await self.token()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/autodarts/session.py", line 80, in token
    await self.refresh_token()
  File "/usr/local/lib/python3.13/site-packages/autodarts/session.py", line 66, in refresh_token
    raise AutoDartAuthenticationException("Authentication failed") from err
autodarts.session.AutoDartAuthenticationException: Authentication failed
`

**Comment by misy1337** [comment]
I've merged my code into this branch. So if you update and use correct CLIENT_ID + CLIENT_Secret it should work. Maybe you find some valid credentials inside the darts-caller.py in a different repo...

**Comment by Snago636** [comment]
Unfortunately it doesn't work with the new version either. Could it be something to do with the Python version?
Or could it be because the AUTODARTS_CLIENT_ID is wrong? I took the board ID from https://play.autodarts.io/boards

**Comment by misy1337** [comment]
Client ID / Secret is like an API Key. It's not your Board ID or user or whatever ... that's why I said look into another repo... maybe other Autodart extensions can provde you a valid Secret / id ...

**Comment by RONMAN87** [comment]
Hi, after updating and inserting the client ID / API key into const.py and restarting, I unfortunately get the same result. The login still throws the same error. Thank you for help.

**Comment by a-jey** [comment]
You may take a deeper look into the darts-caller,py from the darts-hub caller.plugin.

https://github.com/lbormann/darts-caller

**Comment by Snago636** [comment]
Now it worked. Thank you very much

**Comment by RONMAN87** [comment]
It works! Thank you so mutch for you help. Can I donate some think?

**Comment by a-jey** [comment]
> It works! Thank you so mutch for you help. Can I donate some think?

To see you guys happy that it works... is all it needs :-)

**Comment by Pepe-Lange** [comment]
I would be very happy if I could use this addon as well; I just can't get past the error when logging in.
best regards


hello i have fix it self, thanks for this integration

**Comment by edwinstevens** [comment]
But what is the solution?

**Comment by a-jey** [comment]
@Pepe-Lange @edwinstevens 
I guess you both use the wrong credentials.

Just follow my hint some comments above.
